name: wRNN
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - ffmpeg=4.2.2
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.5
  - kornia=0.3.0
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - monai=0.8.0
  - moviepy=1.0.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.1.5
  - pillow=8.3.1
  - python=3.6.13
  - python-dateutil=2.8.2
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pyyaml=5.4.1
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - seaborn=0.11.2
  - torchtext=0.11.2
  - torchvision=0.2.1
  - tqdm=4.63.0
  - yaml=0.2.5
  - wandb